# Generated by Django 3.2.25 on 2026-04-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, default='Free Size', max_length=20, null=True),
        ),
    ]
