# Generated by Django 3.2.25 on 2026-04-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20260429_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Used to calculate profit', max_digits=10),
        ),
    ]
