# Generated by Django 3.2.25 on 2026-04-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_specialoffer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['color_name', 'size']},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, default='Default', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_hex',
            field=models.CharField(default='#000000', help_text='HEX code e.g. #FF0000. Use #000000 if not sure.', max_length=7),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_name',
            field=models.CharField(default='Default', help_text='e.g. Red, Blue, etc.', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'size', 'color_name')},
        ),
    ]
