# Generated by Django 3.2.25 on 2026-04-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20260429_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['size']},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'size')},
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color_hex',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color_name',
        ),
    ]
