# Generated by Django 3.2.25 on 2026-05-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20260429_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, this will be the selling price. The regular price will be shown as a strikethrough.', max_digits=10, null=True),
        ),
    ]
