# Generated by Django 3.2.25 on 2026-05-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_free_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='free_shipping_threshold',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Orders above this amount get free shipping. Set to 0 to disable.', max_digits=10),
        ),
    ]
