# Generated by Django 3.2.25 on 2026-05-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_productvariant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=models.ImageField(blank=True, help_text='Size chart image for this product', null=True, upload_to='size_charts/'),
        ),
    ]
