# Generated by Django 3.2.25 on 2026-05-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_size_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('XXS(30)', 'XXS(30)'), ('XS(32)', 'XS(32)'), ('S(34)', 'S(34)'), ('M(36)', 'M(36)'), ('L(38)', 'L(38)'), ('XL(40)', 'XL(40)'), ('XXL(42)', 'XXL(42)'), ('Free Size', 'Free Size')], max_length=10),
        ),
    ]
