# Generated by Django 3.2.25 on 2026-05-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_productvariant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='numeric_size',
            field=models.CharField(blank=True, help_text='e.g. 34, 36-38 (optional)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('Free Size', 'Free Size')], max_length=10),
        ),
    ]
