# Generated by Django 3.2.25 on 2026-05-14 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20260513_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('material', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum'), ('artificial', 'Artificial/Fashion'), ('diamond', 'Diamond')], default='artificial', max_length=50)),
                ('purity', models.CharField(blank=True, help_text='e.g. 22K, 18K, 925 Sterling', max_length=50)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, help_text='Weight in grams', max_digits=10, null=True)),
                ('stone_type', models.CharField(blank=True, max_length=100)),
                ('is_exclusive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Jewelry Items',
            },
            bases=('store.product',),
        ),
    ]
