# Generated by Django 3.2.25 on 2026-05-14 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_jewelry'),
    ]

    operations = [
        migrations.CreateModel(
            name='JewelryMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Jewelry Materials',
            },
        ),
        migrations.RemoveField(
            model_name='jewelry',
            name='material',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('6', 'Ring Size 6'), ('7', 'Ring Size 7'), ('8', 'Ring Size 8'), ('9', 'Ring Size 9'), ('10', 'Ring Size 10'), ('11', 'Ring Size 11'), ('12', 'Ring Size 12'), ('2.2', 'Bangle 2.2'), ('2.4', 'Bangle 2.4'), ('2.6', 'Bangle 2.6'), ('2.8', 'Bangle 2.8'), ('Free Size', 'Free Size')], max_length=10),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='material_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jewelry_items', to='store.jewelrymaterial', verbose_name='Material'),
        ),
    ]
