# Generated by Django 3.2.25 on 2026-05-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20260514_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, help_text='Total stock for one-size items. If using variants, this will be ignored.'),
        ),
    ]
