# Generated by Django 3.2.25 on 2026-05-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(help_text='Standard: XXS-XXL, 6-12 (Ring), 2.2-2.8 (Bangle). You can also type custom sizes.', max_length=20),
        ),
    ]
